print("Program which accepts a sequence of comma-separated numbers from user and generate a list and tuple with those numbers")
l=input("Enter the comma separated numbers : ")
l2=l.split(',')
print(l2)
print(tuple(l2))